# Generated by Django 5.0.6 on 2024-07-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="components",
            field=models.ManyToManyField(to="spells.component"),
        ),
        migrations.AddField(
            model_name="spell",
            name="duration",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="spells.duration",
            ),
            preserve_default=False,
        ),
    ]
